trainset_3d: ['Human36M']
trainset_2d: ['CrowdPose']


lr_dec_epoch: [17]
end_epoch: 18
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 1

num_thread: 24
train_batch_size: 32
test_batch_size: 32
enc_layers: 2
dec_layers: 4
weight_decay: 0.01
# max_norm: 0.1
use_cls_token: False
upsample_net: True
update_bbox: True